apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.grafanavk.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ .Values.services.grafanavk.name }}
      port: 80
      protocol: TCP
      targetPort: {{ .Values.services.grafanavk.port }}
  selector:
    app: grafanavk
  type: ClusterIP
status:
  loadBalancer: {}