apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.tempo.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ .Values.services.tempo.name }}
      port: 4317
      protocol: TCP
      targetPort: {{ .Values.services.tempo.port }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
status:
  loadBalancer: {}
