apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace }}  # This will automatically use the namespace where the Helm release is deployed
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.auth.tempo.username .Values.auth.tempo.password | b64enc | quote }}