{{- if .Values.ingresses.tempo.mTLS_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: my-client-ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.ingresses.tempo.clientCA | b64enc }}
{{- end }}