{{- if .Values.auth.tempo.mTLSEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: my-client-ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.auth.tempo.clientCA | b64enc }}
{{- end }}