apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true" 
  name: tempo-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /  # Match gRPC paths
            pathType: Prefix
            backend:
              service:
                name:  {{ .Values.services.tempo.name }}
                port:
                  number: 443
      host: {{ .Values.ingresses.tempo.host }}
  tls:
  - hosts:
    - {{ .Values.ingresses.tempo.host }}
    secretName: tempo-tls-secret