apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  name: grafana-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Values.services.grafanavk.name }}
                port:
                  number: 80
      host: {{ .Values.ingresses.grafana.host }}
  tls:
  - hosts:
    - {{ .Values.ingresses.grafana.host }}
    secretName: grafanavk-tls-secret