---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tempo-exporter-example-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tempo-exporter-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingresses.tempoExporter.host }}
  dnsNames:
  - {{ .Values.ingresses.tempoExporter.host }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-verify-client: "off"
    {{- if .Values.ingresses.tempoExporter.auth_enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: "{{ .Release.Namespace }}/basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end }}
  name: tempo-ingress-ext
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /  # Match gRPC paths
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.tempo_exporter.name }}
                port:
                  number: 443
      host: {{ .Values.ingresses.tempoExporter.host }}
  tls:
  - hosts:
    - {{ .Values.ingresses.tempoExporter.host }}
    secretName: tempo-exporter-tls