apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: {{ .Release.Namespace }}
data:
  tempo.yaml: |
    stream_over_http_enabled: true
    server:
      http_listen_port: 3200
      log_level: debug

    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317" 

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h                

    metrics_generator:
      registry:
        external_labels:
          source: tempo
      storage:
        path: /var/tempo/generator/wal
      traces_storage:
        path: /var/tempo/generator/traces

    storage:
      trace:
        backend: local                     
        wal:
          path: /var/tempo/wal             
        local:
          path: /var/tempo/blocks
